apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rhino-ingress
  namespace: dev
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "gce"
    #kubernetes.io/ingress.class: nginx
    # seteamos balanceo por rate
    nginx.ingress.kubernetes.io/limit-rps: "5"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
    - hosts:
        - api-dev.rhinox.io
      secretName: dev-rhino-secret
  rules:
  - host: api-dev.rhinox.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-rhino-deployment-service
            port:
              number: 80
  defaultBackend:
    service:
      name: dev-rhino-deployment-service
      port:
        number: 80