apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: default
data:
  tls.crt: MIIGRDCCBSygAwIBAgIRAIYuFTXJbwP1T1BTDkqeZ8QwDQYJKoZIhvcNAQELBQAw
    gY8xCzAJBgNVBAYTAkdCMRswGQYDVQQIExJHcmVhdGVyIE1hbmNoZXN0ZXIxEDAO
    BgNVBAcTB1NhbGZvcmQxGDAWBgNVBAoTD1NlY3RpZ28gTGltaXRlZDE3MDUGA1UE
    AxMuU2VjdGlnbyBSU0EgRG9tYWluIFZhbGlkYXRpb24gU2VjdXJlIFNlcnZlciBD
    QTAeFw0yMzA2MDMwMDAwMDBaFw0yNDA2MDIyMzU5NTlaMBwxGjAYBgNVBAMTEWFw
    aS1kZXYucmhpbm94LmlvMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    4aV8vSipz4YoaQu0nfZGicBVMXHb4JPGN+6g10QulKn9a5Qdx1SUGOuZ+5G7lNeE
    ulj2hjgFtvVtkg4wj4TXviwnBldC0Xj8bWFhMDfS6VThiU84vcTUAAxXff/Ti+Zy
    sigL1evPsgOvrvLr9+vdb3MfRI7HoM6YfTxDzkf9FDUf75Nb/F5Jvx3csmTS4Hxj
    euB5RiQrLJJSD+8h5mJHkFIkB9jNjhzTaEInXhUCSeAwWSELRtwzGsHKSalE9lKf
    thUEIYezncQMhXIpdgxajhsO+ElMMNBOqjoi4SOBzcjGCEw+zkdyMcYZvaqvgDn0
    a3BZpLRUgoqmjiiiNzss9wIDAQABo4IDCzCCAwcwHwYDVR0jBBgwFoAUjYxexFSt
    iuF36Zv5mwXhuAGNYeEwHQYDVR0OBBYEFEi+M53+SQMtOagypgaaCbEnaM6oMA4G
    A1UdDwEB/wQEAwIFoDAMBgNVHRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMB
    BggrBgEFBQcDAjBJBgNVHSAEQjBAMDQGCysGAQQBsjEBAgIHMCUwIwYIKwYBBQUH
    AgEWF2h0dHBzOi8vc2VjdGlnby5jb20vQ1BTMAgGBmeBDAECATCBhAYIKwYBBQUH
    AQEEeDB2ME8GCCsGAQUFBzAChkNodHRwOi8vY3J0LnNlY3RpZ28uY29tL1NlY3Rp
    Z29SU0FEb21haW5WYWxpZGF0aW9uU2VjdXJlU2VydmVyQ0EuY3J0MCMGCCsGAQUF
    BzABhhdodHRwOi8vb2NzcC5zZWN0aWdvLmNvbTAzBgNVHREELDAqghFhcGktZGV2
    LnJoaW5veC5pb4IVd3d3LmFwaS1kZXYucmhpbm94LmlvMIIBfwYKKwYBBAHWeQIE
    AgSCAW8EggFrAWkAdgB2/4g/Crb7lVHCYcz1h7o0tKTNuyncaEIKn+ZnTFo6dAAA
    AYiBx32VAAAEAwBHMEUCIQCx9pe3eTrYhdzscM6id77kL2llZqgXRmTHnUGr8wh2
    igIgavf1vaZcoOSFDeD4hHk4Z3lIUy0qJVcEiWRJ97UMy7sAdwDatr9rP7W2Ip+b
    wrtca+hwkXFsu1GEhTS9pD0wSNf7qwAAAYiBx33mAAAEAwBIMEYCIQDNlhV4sBJ5
    TAwVk+sjMvjKjbRwhnGbGZ39xpYxfHpUqAIhAIwSknzYBLwJMd6kvjgPPAcLJypK
    xXlIQIgSYcfLHDuYAHYA7s3QZNXbGs7FXLedtM0TojKHRny87N7DUUhZRnEftZsA
    AAGIgcd9wAAABAMARzBFAiEAmt+r2Tad5oRiZdFcvfe7E8ArZxRcuu/lSD+CiyRQ
    ps8CIHvBqqlqs4+o5S74yWUAl2H0QjlZU0Yj/M8HUjZtYAUhMA0GCSqGSIb3DQEB
    CwUAA4IBAQC3bX8LkUylky1jGehOjDlZgjFht7ghKA82emRt8pQlO+5eIF7oneP+
    LpecjTk5rE5zYcEXo/7iWADRs/FP8EpipCrFaQ9WlOkiVn5zEKzck0DMQEV3g/zN
    tSphSr9W7JaaFxID23VNlgy7ACQcKZ9+GcUxUd6BhRXssiQx8JqoUjxzDpMUlLpK
    odgv5Aue4pwj8sPz6jgdoH8QRDG4JIqRzn+dEBiJG+F/VaCisfo+OoXGvaUK8ZnH
    82K1ea+IQhH7Pf3DRcVV6bS1UxTUXrYZwgVTNXQ6cZ/eAs9PSl4Q/YPyv7ESu+1g
    qMMG/z9MN5Vkava1FlRelGhKEAXMUNop 
  tls.key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDhpXy9KKnPhihp
    C7Sd9kaJwFUxcdvgk8Y37qDXRC6Uqf1rlB3HVJQY65n7kbuU14S6WPaGOAW29W2S
    DjCPhNe+LCcGV0LRePxtYWEwN9LpVOGJTzi9xNQADFd9/9OL5nKyKAvV68+yA6+u
    8uv3691vcx9Ejsegzph9PEPOR/0UNR/vk1v8Xkm/HdyyZNLgfGN64HlGJCssklIP
    7yHmYkeQUiQH2M2OHNNoQideFQJJ4DBZIQtG3DMawcpJqUT2Up+2FQQhh7OdxAyF
    cil2DFqOGw74SUww0E6qOiLhI4HNyMYITD7OR3Ixxhm9qq+AOfRrcFmktFSCiqaO
    KKI3Oyz3AgMBAAECggEBAJGMLi7RaN88WRqQ+1scvRkjn5A6MirlBumTGdpg1277
    S0S2EJM/ohuE9RkJQqbacXnF4pZm0oDWRGv+jSI1/PdlAXMcnDQDx0dCle8FQx1Q
    q/3mxOHbcSfqzhCvEKRf7EGwhRnidmEL8al2dfDACmBWMKgHNQsr176IPfB0DPGX
    sFC+UQw41hwMTR8kNIb9k4q1K6BYM4ZMvYDsP9Xy6SzaRsrLgV9a861kuTfs8PB5
    ubPxyRmcOd08SO3ayvXnJNFrt46Sprxh6m9CNzAuySmUlRp70xFrIPYG6/cxYeCS
    nExI37eFmcjjNNnOpfNBpR4NvZn+mxlySkcqoaEoAgkCgYEA/daE/rF6yAz8RYyZ
    448jDhdAF1377Pb/eI73YODvZIwbW9PIYrYOnR7PC02ySlCzyIJnB7f7og5PbWXg
    RtHhg11Su4ZAm+z9KzzV3DEWF1LAQPYgtPSQrdRt5q0SD63nv7gUYhHZdktSbS08
    Eny6tTLvhIXvnui8cqhKsO7vMhUCgYEA45F/YWOcBvGmF4kZ3PFsW55y7luPGlM+
    7bI0G7mYLAuyQebcrlZozTvKjYE5SQDB5+qeAVVNUjjgtkYONNpcFJLX+EeYq1tW
    LmkC+G4i0dVYVGyaZT4c0Rl6nTfCl4H5pH/e8BHvyKPsDFyrZD2LicIcnB+3yRtA
    5Yg5u45UQdsCgYEA87Cvq2gtrMKyqf5qesme6NcvY3+J7RvPdSkjmvE3QjszxLuU
    BBgt/W9na72ira++eX+fdAyQWisM28TTRIoXyyqb04X2nvssrgbQdXz2bVu3UGY6
    Th8AirGG9M8wqLbW5vrNLr1eHTAAqOmlY0Y1ZOHKilqfCdr7l8OzORuZrWUCgYBP
    Lw13wcVE1UjJ37bUHl1p89RiBBHjQxwecWeYThgZG2jHbaFUOFT3NNriKhjYwh62
    p/ia1ie1eH0Yb3/5/BEWR5JGngMNfRabx4Z1Ez2ibe3yUmfW2qoESC1WD1TyixNm
    nefg+RzKX99+3a/1jUTEhnqWCKNWotkOBTyxenDvCQKBgElb7Yi4Iu7LtqF9qbLe
    MoGIz/DyiZwjuoQZPBdm4m98cYRqvPaEmrEhjhEv4nQrseQn6LvrRM89MJEiahD2
    eu4M/dIJvPeB+NxBTACQOjvQsXHXJzZF/P4s1+ibpaz//sym+Ra9A78INh/R9L16
    YLmSRVcfhj+Tp9yxZrSryXDT
type: kubernetes.io/tls