apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rhino-deployment
spec:
  maxReplicas: 15
  minReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rhino-deployment
  targetCPUUtilizationPercentage: 80