apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rhino-ingress
  namespace: dev
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api-dev.rhinox.io
      secretName: rhino-certificado
  rules:
    - host: "api-dev.rhinox.io"
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: rhino-service
              port:
                number: 80