apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
namePrefix: prod-
bases:
  - ../base
resources:
  - namespace.yaml
patches:
  - path: rhino-deployment-patch.yaml
    target:
      kind: Deployment
      name: rhino-deployment