apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
commonLabels:
  env: prod
namePrefix: prod-
bases:
  - ../base
resources:
  - namespace.yaml
patchesStrategicMerge:
 - rhino-deployment-patch.yaml