apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: rhino-hpa
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rhino-deployment
  targetCPUUtilizationPercentage: 80